baseURL = "https://ipark-cs.github.io"
languageCode = "en-us"
title = "iPark memoization"
pluralizelisttitles = false
summarylength = 0
enableGitInfo = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[module]
  [[module.imports]]
    path = "github.com/qdzhang/hugo-notepadium-mod"

disableKinds = ["taxonomy", "taxonomyTerm"]

# Configure chroma highlight
# Reference https://gohugo.io/content-management/syntax-highlighting/
# https://gohugo.io/getting-started/configuration-markup#highlight
[markup.highlight]
codeFences = true
guessSyntax = true
noClasses = true
style = "dracula"

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[permalinks]
    #"/" = "/:year/:month/:filename/"
     projects = "/projects/:slug"
     research = "/research/:slug"
     leetcode = "/leetcode/:slug"
     hackkerrank = "/hackerrank/slug"
     dsa = "/dsa/:slug"
     epi = "/epi/:slug"

[author]
    name = "ipark"  # Change to your name

[params]
author = "ipark"
description = "ipark memoization"
style = "light"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
slogan = ""

# If you use custom css files, declare them here
[params.assets]
css = ["css/fonts.css", "css/custom.css"]

[params.comments]
enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.math]
enable = false # load math globally, default: false. You can always enable math on per page.
use = "katex"  # builtin: "katex", "mathjax".  default: "katex"

[params.nav]
showCategories = false       # /categories/
showTags = true            # /tags/

# You can add taxonomies in there, then link new pages in [[params.nav.custom]]
# Reference https://gohugo.io/content-management/taxonomies/
[taxonomies]
  #category = "categories"
  tag = "tags"

[[params.nav.custom]]
title = "cs.Projects"
url = "/projects/"
#
#
[[params.nav.custom]]
title = "Resume"
url = "/about/"

[[params.nav.custom]]
title = "bio.Research"
url = "/research/"

#[[params.nav.custom]]
#title = "EPI"
#url = "/epi/"

#[[params.nav.custom]]
#title = "LeetCode"
#url = "/leetcode/"

#[[params.nav.custom]]
#title = "HackerRank"
#url = "/hackerrank/"

#[[params.nav.custom]]
#title = "DSA"
#url = "/dsa/"

