baseURL = "https://ipark-cs.github.io"
languageCode = "en-us"
title = "iPark memoization"
<<<<<<< HEAD
pluralizelisttitles = false
summarylength = 0
=======
>>>>>>> 97faec09aef23dc2c34f7a68439f8f66a218565a

[module]
  [[module.imports]]
    path = "github.com/qdzhang/hugo-notepadium-mod"

<<<<<<< HEAD
disableKinds = ["taxonomy", "taxonomyTerm"]

=======
>>>>>>> 97faec09aef23dc2c34f7a68439f8f66a218565a
# Configure chroma highlight
# Reference https://gohugo.io/content-management/syntax-highlighting/
# https://gohugo.io/getting-started/configuration-markup#highlight
[markup.highlight]
codeFences = true
guessSyntax = true
noClasses = true
style = "dracula"

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

<<<<<<< HEAD
#[permalinks]
#    #"/" = "/:year/:month/:filename/"
     projects = "/projects/:slug"
     research = "/research/:slug"
     leetcode = "/leetcode/:slug"
     hackkerrank = "/hackerrank/slug"
     dsa = "/dsa/:slug"
     epi = "/epi/:slug"
=======
[permalinks]
    #"/" = "/:year/:month/:filename/"
    projects = "/projects/:slug"
    code = "/code/:slug"
>>>>>>> 97faec09aef23dc2c34f7a68439f8f66a218565a

[author]
    name = "ipark"  # Change to your name

[params]
author = "ipark"
description = "ipark memoization"
style = "light"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
<<<<<<< HEAD
slogan = ""
=======
#logo = "https://cdn.jsdelivr.net/gh/qdzhang/littlezhang.com/static/logo.png"
slogan = ""
#license = "<a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/><img alt=Creative Commons License style=border-width:0 src=https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png /></a><br />This work is licensed under a <a rel=license href=http://creativecommons.org/licenses/by-nc-sa/4.0/>Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>."
>>>>>>> 97faec09aef23dc2c34f7a68439f8f66a218565a

# If you use custom css files, declare them here
[params.assets]
css = ["css/fonts.css", "css/custom.css"]

[params.comments]
enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.math]
enable = false # load math globally, default: false. You can always enable math on per page.
use = "katex"  # builtin: "katex", "mathjax".  default: "katex"

[params.nav]
<<<<<<< HEAD
showCategories = false       # /categories/
showTags = true            # /tags/
=======
showCategories = false        # /categories/
showTags = false             # /tags/
>>>>>>> 97faec09aef23dc2c34f7a68439f8f66a218565a

# You can add taxonomies in there, then link new pages in [[params.nav.custom]]
# Reference https://gohugo.io/content-management/taxonomies/
[taxonomies]
<<<<<<< HEAD
  #category = "categories"
  tag = "tags"

[[params.nav.custom]]
title = "cs.Projects"
url = "/projects/"
#
#
[[params.nav.custom]]
title = "Resume"
url = "/about/"

[[params.nav.custom]]
title = "bio.Research"
url = "/research/"

[[params.nav.custom]]
title = "EPI"
url = "/epi/"

#[[params.nav.custom]]
#title = "LeetCode"
#url = "/leetcode/"

#[[params.nav.custom]]
#title = "HackerRank"
#url = "/hackerrank/"

#[[params.nav.custom]]
#title = "DSA"
#url = "/dsa/"
=======
  category = "categories"
  tag = "tags"

[[params.nav.custom]]
title = "Projects"
url = "/projects/"

[[params.nav.custom]]
title = "Code"
url = "/code/"

[[params.nav.custom]]
title = "Resume"
url = "/about/"

>>>>>>> 97faec09aef23dc2c34f7a68439f8f66a218565a

